NAME = test
COMPLIER = cc
FLAG = -Wall -Wextra -Werror

SRCS = ft_isalpha.c test.c
OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(COMPLIER) $(FLAG) $(OBJS) -o $(NAME)

%.o: %.c
	$(COMPLIER) $(FLAG) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re